### ISSUE TITLE
Support for passing/returning path expressions

### ISSUE THREAD

**Issue by jonasschmidt** [Cleidiano/warpath#27]
Hey there!

Would it be possible to support passing a compiled expression to `Warpath.query`? We have a use case where we have a limited set of paths that we query over and over again on different data, and compiling the path only once would save us a ton of computation time.

Also, it would be great to be able to pass an option to return the compiled path from `Warpath.query`, instead of stringifying it with `Warpath.Element.Path.bracketify`. We want to use the returned path to then patch the term, and not having to re-compile the path would also make it easier to handle that case.

On a higher level, support for patching the term, instead of just querying it (the way that https://github.com/ostrovok-team/ejsonpath does), would be even better. But probably q lot more work.

Cheers and thanks for the great library 👍

**Comment by jonasschmidt** [comment]
https://github.com/Cleidiano/warpath/pull/28

**Comment by cleidiano** [comment]
Hi @jonasschmidt,
Add support to compiled expression make total sense, I'am very happy that you opened up a PR.
Currently I'am refactoring the parser grammar that could reflect in the Expression token names handled by Warpath, it's almost ready, but it need some adjust yet.

After the refactoring finish I think that support a option to return compiled expression path could be addressed.
I will keep your PR open until the refactoring is finished, this features will be  released on version `0.3.0`.

Cheers.

**Comment by jonasschmidt** [comment]
Alright, that sounds good 👍

**Comment by cleidiano** [comment]
Return a path token where added at #50, and will be included in the next release. About support for patching I not sure if the Warpath will support this, currently the work is to make the Api stable and add missing features that is part of jsonpath.
