### ISSUE TITLE
Support for filter expressions with deep matching?

### ISSUE THREAD

**Issue by jonasschmidt** [Cleidiano/warpath#68]
Hey.

I'm trying to figure out if using subpaths in filter expressions is something that could be supported by warpath. It seems like some libraries do, so for an input of:
```json
[
  {
    "address": {
      "city": "Berlin"
    }
  },
  {
    "address": {
      "city": "London"
    }
  }
]
```

and a path:
```
$[?(@.address.city=='Berlin')]
```

https://jsonpath.com/ gives me the expected output of:
```json
[
  {
    "address": {
      "city": "Berlin"
    }
  }
]
```

Is that just an obscure undocumented feature, or could this be something to support? Alternatively, is there another way to achieve the same result?

**Comment by cleidiano** [comment]
Currently  it's not supported, but it certainly is a legitime feature, I will explore that in the next days.
There isn't another way to workaround just now because the parser is not capable of parse such expression.

**Comment by jonasschmidt** [comment]
Great, thanks for looking into it 👍
