### ISSUE TITLE
Filter expressions and deep path traversal

### ISSUE THREAD

**Issue by jonasschmidt** [Cleidiano/warpath#82]
Hey,

I just tried to upgrade to get the awesome support for deep paths on filter expressions and found a bug that was caught by one of our unit tests.

One level down after a filter expression still works as expected:
```elixir
iex(10)> Warpath.query([%{"id" => 1, "foo" => %{"bar" => "baz"}}], "$[?(@.id==1)].foo")
{:ok, [%{"bar" => "baz"}]}
iex(11)> Warpath.query([%{"id" => 1, "foo" => %{"bar" => "baz"}}], "$[?(@.id==1)].foo", result_type: :path)
{:ok, ["$[0]['foo']"]}
```

But trying to traverse one level deeper gives an unexpected result:
```elixir
iex(12)> Warpath.query([%{"id" => 1, "foo" => %{"bar" => "baz"}}], "$[?(@.id==1)].foo.bar")
{:ok, nil}
iex(13)> Warpath.query([%{"id" => 1, "foo" => %{"bar" => "baz"}}], "$[?(@.id==1)].foo.bar", result_type: :path)
{:ok, "['bar']"}
```

**Comment by cleidiano** [comment]
Hi @jonasschmidt , thanks for report and the use of the master branch version!
I have been fixed the issue, please given another try if you have any issue feel free to open up a new one.

**Comment by jonasschmidt** [comment]
Yes, that fixed the issue. Thank you for the quick response! 🚀
I have another smaller (maybe related?) issue that I will open separately. Maybe it's just something that needs clarification: https://github.com/Cleidiano/warpath/issues/84
