### ISSUE TITLE
error when combining filters and field access

### ISSUE THREAD

**Issue by mmmries** [Cleidiano/warpath#92]
Hi @Cleidiano and thanks again for the awesome library. I came across what I think is an edge case in the library and I'm hoping to get your thoughts on it before I try to open a PR for this.

```elixir
data = [%{"Amount" => 1, "Id" => 1}, %{"Id" => 2}]

Warpath.query(data, "$[*].Amount") # => {:ok, [1]}
Warpath.query(data, "$[?(@.Id == 1)].Amount") # => {:ok, [1]}

Warpath.query(data, "$[?(@.Id == 0)].Amount") # Error
```

The error message looks like this:

```
** (FunctionClauseError) no function clause matching in Keyword.has_key?/2    
    
    The following arguments were given to Keyword.has_key?/2:
    
        # 1
        []
    
        # 2
        "Amount"
    
    Attempted function clauses (showing 1 out of 1):
    
        def has_key?(keywords, key) when is_list(keywords) and is_atom(key)
    
    (elixir 1.10.3) lib/keyword.ex:802: Keyword.has_key?/2
    (warpath 0.4.0) lib/warpath/query/identifier_operator.ex:28: Warpath.Query.IdentifierOperator.Map.evaluate/3
    (warpath 0.4.0) lib/warpath.ex:94: Warpath.dispatch/2
    (elixir 1.10.3) lib/enum.ex:3686: Enumerable.List.reduce/3
    (elixir 1.10.3) lib/enum.ex:2161: Enum.reduce_while/3
    (warpath 0.4.0) lib/warpath.ex:72: Warpath.query/3
```

It seems to only happen if you have filtered out all possible matches, but you still try to access a field. I'm thinking that in this case once the filter has identified no potential matches in the list we should return early with `{:ok, []}`, but want to make sure I'm headed in the right direction before I open a PR on your project.

**Comment by cleidiano** [comment]
Hi @mmmries thank you for report!
It's certainly a bug, it is around `Warpath.Query.Accessible` module. 
To return early we need to halt de execution at `Warpath` module, could you submit a PR?

**Comment by mmmries** [comment]
👍 I will definitely open a PR. It will be my first PR of this year's [Hacktoberfest](https://hacktoberfest.digitalocean.com/) 🎉
